targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        options:
          # enable_cached_builds: true
        generate_for:
            - lib/**_page.dart
            - lib/**router.dart